---
- hosts: oraclerac
 
  tasks:
    # physical
    - name: create partion /dev/sdb
      parted:
       device: /dev/sdb
       number: 1
       state: present

    - name: Get udev id
      command: '/usr/lib/udev/scsi_id -g -u -d /dev/sdb1'
      register: disksdbnode1
      when: ansible_hostname == "rac-node01" 

    - name: Show id
      debug:
        var: disksdbnode1.stdout
      when: ansible_hostname == "rac-node01"