---
- hosts: oraclerac
 
  tasks:
    # physical
    - name: create partion /dev/sdb
      parted:
       device: /dev/sdb
       number: 1
       flags: [ lvm ]
       state: present
    
    - name: create volume group vg.data
      lvg:
       vg: vg.data
       pvs: /dev/sdb1
    
    # oracledb
    
    - name: create logical oracledb disk on vg.data
      lvol:
       vg: vg.data
       lv: lv.oracledb
       size: 30G
    
    - name: create filesystem xfs on lv.oracledb
      filesystem:
       fstype: xfs
       dev: /dev/mapper/vg.data-lv.oracledb
    
    - name: create directory for lv.oracledb
      file:
       path: /u01
       state: directory
    
    - name: add fstab entry
      mount: 
       name: /u01 
       src: /dev/mapper/vg.data-lv.oracledb
       fstype: xfs 
       opts: defaults
       state: present
        
    # mount all
    
    - name: mount disk
      shell: mount -a
      args:
       warn: false