---
- hosts: oraclerac
 
  tasks:
   # Configure Udev
    - name: Configure SCSI as trusted device
      lineinfile:
       path: /etc/scsi_id.config
       line: 'options=-g'
       create: yes

    # physical
    - name: create partion /dev/sdb
      parted:
       device: /dev/sdb
       number: 1
       flags: [ lvm ]
       state: present
    
    - name: create partion /dev/sdc
      parted:
       device: /dev/sdc
       number: 1
       state: present
      when: ansible_hostname == "dbrac1"

    - name: create partion /dev/sdd
      parted:
       device: /dev/sdd
       number: 1
       state: present
      when: ansible_hostname == "dbrac1"

    - name: create partion /dev/sde
      parted:
       device: /dev/sde
       number: 1
       state: present
      when: ansible_hostname == "dbrac1"

    - name: create partion /dev/sdf
      parted:
       device: /dev/sdf
       number: 1
       state: present
      when: ansible_hostname == "dbrac1"

    - name: create volume group vg.data
      lvg:
       vg: vg.data
       pvs: /dev/sdb1
    
    # oracledb
    
    - name: create logical oracledb disk on vg.data
      lvol:
       vg: vg.data
       lv: lv.oracledb
       size: 30G
    
    - name: create filesystem xfs on lv.oracledb
      filesystem:
       fstype: xfs
       dev: /dev/mapper/vg.data-lv.oracledb
    
    - name: create directory for lv.oracledb
      file:
       path: /u01
       state: directory
    
    - name: add fstab entry
      mount: 
       name: /u01 
       src: /dev/mapper/vg.data-lv.oracledb
       fstype: xfs 
       opts: defaults
       state: present
        
    # mount all
    
    - name: mount disk
      shell: mount -a
      args:
       warn: false
