---
- hosts: storagenfs
  vars:

  tasks:
    # physical
    - name: create partion /dev/sdb
      parted:
       device: /dev/sdb
       number: 1
       flags: [ lvm ]
       state: present
    
    - name: create volume group vg.data
      lvg:
       vg: vg.data
       pvs: /dev/sdb1
    
    # datadisk
    
    - name: create logical data disk on vg.data
      lvol:
       vg: vg.data
       lv: lv.disk1
       size: 30G
    
    - name: create filesystem xfs on lv.disk1
      filesystem:
       fstype: xfs
       dev: /dev/mapper/vg.data-lv.disk1
    
    - name: create directory for lv.disk1
      file:
       path: /nfsdisk/disk1
       state: directory
    
    - name: add fstab entry
      mount: 
       name: /nfsdisk/disk1 
       src: /dev/mapper/vg.data-lv.disk1
       fstype: xfs 
       opts: defaults
       state: present
        
    # mount all
    
    - name: mount disk
      shell: mount -a
      args:
       warn: false