---
- hosts: storagenoder
  vars:
    nfs_export: /data
    gluster_volume_name: data
    gluster_server: storage01.redhat.local

  tasks:
    # physical
    - name: create partion /dev/sdb
      parted:
       device: /dev/sdb
       number: 1
       flags: [ lvm ]
       state: present
    
    - name: create volume group vg.data
      lvg:
       vg: vg.data
       pvs: /dev/sdb1
    
    # datadisk
    
    - name: create logical data disk on vg.data
      lvol:
       vg: vg.data
       lv: lv.brick01
       size: 30G
    
    - name: create filesystem xfs on lv.brick01
      filesystem:
       fstype: xfs
       dev: /dev/mapper/vg.data-lv.brick01
    
    - name: create directory for lv.brick01
      file:
       path: /gluster/brick01
       state: directory
    
    - name: add fstab entry
      mount: 
       name: /gluster/brick01 
       src: /dev/mapper/vg.data-lv.brick01
       fstype: xfs 
       opts: defaults
       state: present
        
    # mount all
    
    - name: mount disk
      shell: mount -a
      args:
       warn: false

    - name: create directory for gluster
      file:
       path: /gluster/brick01/data
       state: directory


    # Install Software

    - name: Enable Gluster 4.1 repositories
      yum_repository:
        name: ol7_gluster41
        description: Oracle Linux 7 Gluster 4.1
        baseurl: http://yum.oracle.com/repo/OracleLinux/OL7/gluster41/x86_64

    - name: Enable addons repositories
      yum_repository:
        name: ol7_addons
        description: Oracle Linux 7 Add-ons
        baseurl: http://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64
    
    - name: Enable optional-latest repositories
      yum_repository:
        name: ol7_optional_latest
        description: Oracle Linux 7 Add-ons
        baseurl: http://yum.oracle.com/repo/OracleLinux/OL7/optional/latest/x86_64

    - name: Yum update
      yum:
        name: "*"
        state: latest

    - name: Install gluster software
      yum:
        name: 
          - glusterfs-server
          - nfs-ganesha-gluster
        state: latest

    # Configure firewall
    
    - name: set firewall rules Glusterfs
      firewalld:
        zone: public
        service: glusterfs
        permanent: true
        state: enabled
      notify: reload firewalld

    - name: enable glusterfs-server
      systemd:
        name: glusterd
        state: started
        enabled: yes
    
    # Configure Gluster

    - name: Create a trusted storage pool
      gluster_peer:
        state: present
        nodes:
             - storage02.redhat.local
             - storage03.redhat.local
      when: ansible_hostname == "storage01" 
    
    - name: create gluster volume
      gluster_volume:
        state: present
        name: "{{ gluster_volume_name }}"
        bricks: /gluster/brick01/data
        replicas: 3
        cluster:
             - storage01.redhat.local
             - storage02.redhat.local
             - storage03.redhat.local
      run_once: true
      when: ansible_hostname == "storage01" 

    - name: create directory for ganesha
      file:
       path: /etc/ganesha/exports
       state: directory    

    - name: create ganesha export conf
      template:
       src: templates/export.data.conf.j2
       dest: /etc/ganesha/exports/export.data.conf

    - name: include export.data.conf in ganesha.conf
      lineinfile:
       path: /etc/ganesha/ganesha.conf
       line: '%include "/etc/ganesha/exports/export.data.conf"'
       insertafter: EOF

    - name: enable nfs-ganesha
      systemd:
        name: nfs-ganesha
        state: stopped
        enabled: no

  handlers:
  - name: reload firewalld
    systemd:
      name: firewalld
      state: reloaded