---
- hosts: storagenfs
  vars:

  tasks:
    - name: yum update
      yum:
       name:  "*"
       state: latest

    # physical disk
    - name: create partion /dev/sdb
      parted:
       device: /dev/sdb
       number: 1
       flags: [ lvm ]
       state: present
    
    - name: create volume group vg.data
      lvg:
       vg: vg.data
       pvs: /dev/sdb1
    
    # shared_config
    
    - name: create logical data disk on vg.data
      lvol:
       vg: vg.data
       lv: lv.shared_config
       size: 20G
    
    - name: create filesystem xfs on lv.shared_config
      filesystem:
       fstype: xfs
       dev: /dev/mapper/vg.data-lv.shared_config
    
    - name: create directory for lv.shared_config
      file:
       path: /nfsdisk/shared_config
       state: directory
    
    - name: add fstab entry
      mount: 
       name: /nfsdisk/shared_config 
       src: /dev/mapper/vg.data-lv.shared_config
       fstype: xfs 
       opts: defaults
       state: present

    # shared_grid

    - name: create logical data disk on vg.data
      lvol:
       vg: vg.data
       lv: lv.shared_grid
       size: 20G
    
    - name: create filesystem xfs on lv.shared_grid
      filesystem:
       fstype: xfs
       dev: /dev/mapper/vg.data-lv.shared_grid
    
    - name: create directory for lv.shared_grid
      file:
       path: /nfsdisk/shared_grid
       state: directory
    
    - name: add fstab entry
      mount: 
       name: /nfsdisk/shared_grid 
       src: /dev/mapper/vg.data-lv.shared_grid
       fstype: xfs 
       opts: defaults
       state: present

    # shared_home

    - name: create logical data disk on vg.data
      lvol:
       vg: vg.data
       lv: lv.shared_home
       size: 20G
    
    - name: create filesystem xfs on lv.shared_home
      filesystem:
       fstype: xfs
       dev: /dev/mapper/vg.data-lv.shared_home
    
    - name: create directory for lv.shared_home
      file:
       path: /nfsdisk/shared_home
       state: directory
    
    - name: add fstab entry
      mount: 
       name: /nfsdisk/shared_home 
       src: /dev/mapper/vg.data-lv.shared_home
       fstype: xfs 
       opts: defaults
       state: present

    # shared_data

    - name: create logical data disk on vg.data
      lvol:
       vg: vg.data
       lv: lv.shared_data
       size: 20G
    
    - name: create filesystem xfs on lv.shared_data
      filesystem:
       fstype: xfs
       dev: /dev/mapper/vg.data-lv.shared_data
    
    - name: create directory for lv.shared_data
      file:
       path: /nfsdisk/shared_data
       state: directory
    
    - name: add fstab entry
      mount: 
       name: /nfsdisk/shared_data 
       src: /dev/mapper/vg.data-lv.shared_data
       fstype: xfs 
       opts: defaults
       state: present

    # mount all
    
    - name: mount disk
      shell: mount -a
      args:
       warn: false

    # Configure NFS Storage
    - name: Install NFS
      yum:
        name: nfs-utils
        state: latest

    - name: Enable NFS Service
      systemd:
        name: nfs-server
        enabled: yes
        state: started

    - name: set firewall rules nfs
      firewalld:
        zone: public
        service: nfs
        permanent: true
        state: enabled
      notify: reload firewall

    - name: set firewall rules mountd
      firewalld:
        zone: public
        service: mountd
        permanent: true
        state: enabled
      notify: reload firewall

    - name: set firewall rules rpc-bind
      firewalld:
        zone: public
        service: rpc-binf
        permanent: true
        state: enabled
      notify: reload firewall

    - name: Create NFS export
      blockinfile:
        path: /etc/exports
        block: |
          /nfsdisk/shared_config               *(rw,sync,no_wdelay,insecure_locks,no_root_squash)
          /nfsdisk/shared_grid                 *(rw,sync,no_wdelay,insecure_locks,no_root_squash)
          /nfsdisk/shared_home                 *(rw,sync,no_wdelay,insecure_locks,no_root_squash)
          /nfsdisk/shared_data                 *(rw,sync,no_wdelay,insecure_locks,no_root_squash)
      notify: reload nfs
          
  handlers:
    - name: reload firewall
      systemd: 
        name: firewalld
        state: restarted

    - name: reload nfs
      shell: exportfs -ra
